### ISSUE TITLE
Does it really work?

### ISSUE THREAD

**Issue by vanous** [traktofon/cf-detect#1]
Tested:

https://news.ycombinator.com/
http://jitbit.com/

and icon doesn't change. Any debug info anywhere?

thank you

Firefox 52.0b1 (64-bit)

uname -a
Linux tc-vanek 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux

**Comment by vanous** [comment]
Hmm, turned on debugging but don't see the browser.webRequest.onHeadersReceived.addListener resp. cfdetect being triggered. But i am not too sure i am checking correctly.
thank you

**Comment by traktofon** [comment]
Hi vanous,
thanks for reporting the issue. So far I have only tested on Firefox 51.0.1 (Linux 64-bit, Ubuntu 14.04), and it does work for me (both sites you mentioned, and others as well). I will test with newer (beta/alpha) versions of Firefox to see if I can reproduce the problem. Do you happen to see any error messages in the browser console (Shift+Ctrl+J) when installing/loading the extension, or when visiting any affected page?

**Comment by traktofon** [comment]
Confirmed with Firefox 52.0b9 and 53.0a2.
No error messages on console though.

**Comment by traktofon** [comment]
Got it. Firefox 52 passes lowercased versions of the header names in the responseHeaders object. Will upload a fixed version soon.

**Comment by traktofon** [comment]
Fixed version uploaded to AMO. Until it is approved there, new version can be installed manually.

**Comment by vanous** [comment]
thank you, it works
