### ISSUE TITLE
No issue, question about "all requests" analysis

### ISSUE THREAD

**Issue by ghost** [traktofon/cf-detect#6]
Hi,

I've just installed Detect Cloudflare 6.1 on Firefox 51.0.1 (x64). Runs flawlessly.

I have a question, or rather a quest for confirmation, regarding what is mentioned here about cf-detect:

>  This extension analyzes all requests made by the browser, which may impact performance.

I experience up to now no perceptible delay. Maybe is this also due to the fact that 3rd-partie sites are excessively filtered here with the uBlockO add-on ...

My question therefor is : by "all requests" must we understand all "true" requests (those effectively operated hence not those blocked be it here with uBlockO) or "all" requests initially performed by the site independently of the fact they be blocked or not?

I believe it is all "true" requests, but I only wish your confirmation on this point, which would maybe (partially) explain why I encounter no delay.

Thanks!

**Comment by traktofon** [comment]
Hi zymase,

I believe it is _not_ all requests. This extension uses the webRequest API to listen to the `onHeadersReceived` event, without any filtering of the requests. Firefox does have other APIs (especially webNavigation) which can hook more deeply into the lifetime of requests. I think it is possible that some extensions block some requests before they are made, and for those the `onHeadersReceived` event will not fire, I guess.

For example, in a clean profile, on stackoverflow.com I see CF requests from two domains (imgur.com and adzerk.net), but in a profile with uBlock0 and Ghostery, I only see one domain (imgur.com).

As for the performance impact: thanks for reporting that you don't see any perceptible impact. This matches my own experience. Also, Firefox's about:performance never seems to detect any problems with this extension. Currently I don't know how else to measure the impact.

If you are satisfied with the answer, please close this issue. Thanks.

**Comment by ghost** [comment]
OK, @traktofon , that's what I thought and hoped considering I care less to know all requests for Cloudflare programmed in a page then those effectively operated, in a pragmatical rather than analytic approach.

It wasn't an issue, just a wondering and now things are clear. Thanks. I'll close the door as I leave :)
