### ISSUE TITLE
Back/Forward isn't handled

### ISSUE THREAD

**Issue by ghost** [traktofon/cf-detect#7]
_Detect Cloudflare 6.1 / Firefox 51.0.1 (x64)_

_Detect Cloudflare_ doesn't handle detection of page when page is changed to previous/next (same tab). User needs to reload the tab to have the detection updated.

**Comment by traktofon** [comment]
Hi zymase, thanks for the report! You are correct, the icon is not updated correctly. Nowadays many webpages automatically reload when you navigate backward/forward in the tab, so I didn't notice this before.

I think a proper fix would require storing the (potentially large) detection history for each tab. This feels rather heavy for what I feel is little benefit. So I checked how other extensions (uBlock0 and Ghostery) behave in this case. They just reset to zero, without recalling the previous result. I will follow the same approach, and reset the detection status to neutral (grey) until the page is reloaded. Also, I'll add a note to the README pointing out this issue.

**Comment by ghost** [comment]
Now that you mention it ("_Nowadays many webpages automatically reload when you navigate backward/forward in the tab_") I've started wondering on the pertinence of the related setting I've always used in Firefox, and have switched the cache check of pages from _when the page is out of date_ (default) to _every time a page is loaded_ and indeed icon update pseudo issue vanishes.

This problematic concerns indeed all extensions handling page related data, and they are numerous. Another Firefox add-on I use than those you mention, called _CheckMyHTTPS_ encountered the same icon update problem and resolved it as you with coming version 7.0

For Firefox users, with your permission @traktofon , a recall of Firefox page cache update settings available in about:config,

> Check cache of the pages : browser.cache.check_doc_frequency
> 0 : Once per session
> 1 : Every time a page is loaded.
> 2 : Never check for a new version - always load the page from cache.
> 3 : When the page is out of date. (Default) 

So, _Every time a page is loaded_ here it will be even if upcoming version 7.0 will handle cases (0), (2) and (3).

Thanks!
